// Fill out your copyright notice in the Description page of Project Settings.


#include "Character/HBCharacterPlayer.h"

#include "EngineUtils.h"
#include "InputMappingContext.h"
#include "Animation/HBPlayerCharacterAnimInstance.h"
#include "Component/HBCharacterRagdollComponent.h"
#include "Components/CapsuleComponent.h"
#include "Engine/DamageEvents.h"
#include "GameFramework/GameStateBase.h"
#include "GameMode/HBVillageGameMode.h"
#include "Interface/HBInteractableInterface.h"
#include "Net/UnrealNetwork.h"
#include "Stat/HBPlayerStatComponent.h"
#include "Subsystem/HBGameFlowSubsystem.h"
#include "Subsystem/HBGameVoteSubsystem.h"
#include "UI/HBUserHUDWidget.h"
#include "GameState/HBMafiaGameState.h"
#include "Character/Component/HBCharacterMafiaAttackComponent.h"

AHBCharacterPlayer::AHBCharacterPlayer()
{
	// FPS ï¿½Þ½ï¿½ ï¿½ï¿½ï¿½ï¿½
	FPSMeshComponent = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("FPSMesh"));
	FPSMeshComponent->SetupAttachment(GetMesh());
	FPSMeshComponent->FirstPersonPrimitiveType = EFirstPersonPrimitiveType::FirstPerson;
	FPSMeshComponent->SetOnlyOwnerSee(true);

	FPSMeshComponent->SetRelativeScale3D(FVector(0.8f, 0.8f, 0.8f));
	FPSMeshComponent->SetRelativeLocation(FVector(0.f, 0.f, 290.f));


	GetMesh()->FirstPersonPrimitiveType = EFirstPersonPrimitiveType::WorldSpaceRepresentation;
	FPSMeshComponent->SetCollisionProfileName(FName("NoCollision"));

	// FPS Ä«ï¿½Þ¶ï¿½ ï¿½ï¿½ï¿½ï¿½
	FPSCameraComponent = CreateDefaultSubobject<UCameraComponent>(TEXT("FPSCamera"));
	FPSCameraComponent->SetupAttachment(FPSMeshComponent);

	// Ä«ï¿½Þ¶ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ø¼ï¿½ ï¿½Ó¸ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ì±ï¿½
	FPSCameraComponent->SetRelativeLocationAndRotation(FVector(0.0f, -75.0f, 560.0f), FRotator(0.0f, 90.0f, -90.0f));
	FPSCameraComponent->bUsePawnControlRotation = true;

	FPSCameraComponent->bEnableFirstPersonFieldOfView = true;
	FPSCameraComponent->bEnableFirstPersonScale = true;
	FPSCameraComponent->FirstPersonFieldOfView = FPSFieldOfView;
	FPSCameraComponent->FirstPersonScale = FPSViewScale;

	RagdollComponent = CreateDefaultSubobject<UHBCharacterRagdollComponent>(TEXT("Ragdoll"));

	// ï¿½ï¿½ï¿½ï¿½ ï¿½Ô·ï¿½ ï¿½ï¿½ï¿½ï¿½
	static ConstructorHelpers::FObjectFinder<UInputMappingContext> InputMappingContextRef(
		TEXT("/Game/Character/Input/IMC_Player.IMC_Player"));
	if (InputMappingContextRef.Succeeded())
	{
		InputMappingContext = InputMappingContextRef.Object;
	}

	static ConstructorHelpers::FObjectFinder<UInputAction> MoveActionRef(
		TEXT("/Game/Character/Input/Action/IA_Move.IA_Move"));
	if (MoveActionRef.Succeeded())
	{
		MoveAction = MoveActionRef.Object;
	}

	static ConstructorHelpers::FObjectFinder<UInputAction> AttackActionRef(
		TEXT("/Game/Character/Input/Action/IA_Attack.IA_Attack"));
	if (AttackActionRef.Succeeded())
	{
		AttackAction = AttackActionRef.Object;
	}

	static ConstructorHelpers::FObjectFinder<UInputAction> InteractionActionRef(
		TEXT("/Game/Character/Input/Action/IA_Interaction.IA_Interaction"));
	if (InteractionActionRef.Succeeded())
	{
		InteractionAction = InteractionActionRef.Object;
	}

	static ConstructorHelpers::FObjectFinder<UInputAction> MouseLookActionRef(
		TEXT("/Game/Character/Input/Action/IA_MouseLook.IA_MouseLook"));
	if (MouseLookActionRef.Succeeded())
	{
		MouseLookAction = MouseLookActionRef.Object;
	}

	static ConstructorHelpers::FObjectFinder<UInputAction> JumpActionRef(
		TEXT("/Game/Character/Input/Action/IA_Jump.IA_Jump"));
	if (JumpActionRef.Succeeded())
	{
		JumpAction = JumpActionRef.Object;
	}

	// @PHYTODO : ï¿½Ó½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ð¹ï¿½
	static ConstructorHelpers::FObjectFinder<UInputAction> StartActionRef(
		TEXT("/Game/Character/Input/Action/IA_Start.IA_Start"));
	if (StartActionRef.Succeeded())
	{
		StartAction = StartActionRef.Object;
	}

	// ï¿½Þ½ï¿½ ï¿½ï¿½ï¿½ï¿½
	static ConstructorHelpers::FObjectFinder<USkeletalMesh> MeshRef(
		TEXT("/Game/Assets/Character/Mesh/Bear_Add_Mat.Bear_Add_Mat"));
	if (MeshRef.Succeeded())
	{
		GetMesh()->SetSkeletalMesh(MeshRef.Object);
	}

	static ConstructorHelpers::FObjectFinder<USkeletalMesh> FPSMeshRef(
		TEXT("/Game/Assets/Character/Mesh/Bear_Arm_fix1.Bear_Arm_fix1"));
	if (FPSMeshRef.Succeeded())
	{
		FPSMeshComponent->SetSkeletalMesh(FPSMeshRef.Object);
	}

	static ConstructorHelpers::FClassFinder<UHBPlayerCharacterAnimInstance> PlayerAnimInstanceRef(
		TEXT("/Game/Character/Anim/ABP_PlayerCharacter.ABP_PlayerCharacter_C"));
	if (PlayerAnimInstanceRef.Succeeded())
	{
		AnimInstanceClass = PlayerAnimInstanceRef.Class;
	}

	static ConstructorHelpers::FObjectFinder<UAnimMontage> AttackMontageRef(
		TEXT("/Game/Character/Anim/AM_CharacterAttack.AM_CharacterAttack"));
	if (AttackMontageRef.Succeeded())
	{
		AttackMontage = AttackMontageRef.Object;
	}

	// Ä³ï¿½ï¿½ï¿½ï¿½ ï¿½Þ½ï¿½ ï¿½ï¿½ï¿½ï¿½
	GetMesh()->SetRelativeScale3D(FVector(0.2f, 0.2f, 0.2f));
	GetMesh()->SetRelativeLocation(FVector(0.0f, 0.0f, -86.0f));
	GetMesh()->SetRelativeRotation(FRotator(0.0f, -90.0f, 0.0f));
	GetMesh()->SetAnimInstanceClass(AnimInstanceClass);
	FPSMeshComponent->SetAnimInstanceClass(AnimInstanceClass);

	// 1ï¿½ï¿½Äª ï¿½ï¿½ï¿½ï¿½ ï¿½Þ½ï¿½ ï¿½ï¿½ï¿½ï¿½
	FPSCurrentWeapon = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("FPSWeapon"));
	FPSCurrentWeapon->SetupAttachment(FPSMeshComponent, TEXT("RightHandWeaponSocket"));
	FPSCurrentWeapon->SetCollisionProfileName(TEXT("NoCollision"));
	FPSCurrentWeapon->SetIsReplicated(true);
	FPSCurrentWeapon->SetOnlyOwnerSee(true);
	FPSCurrentWeapon->FirstPersonPrimitiveType = EFirstPersonPrimitiveType::FirstPerson;

	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ê±ï¿½È­
	bCanAttack = true;

	//¹«±â Å»/Âø¿ë
	MafiaAttackComp = CreateDefaultSubobject<UHBCharacterMafiaAttackComponent>(TEXT("MafiaAttackComp"));
}

void AHBCharacterPlayer::BeginPlay()
{
	Super::BeginPlay();

	/* ================= Night Flow : Game Start Init ================= */
	if (HasAuthority())
	{
		// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã¿ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½ï¿½ï¿½) ï¿½Ê±ï¿½È­
		Stamina = MaxStamina;
		bExitedHouseThisNight = false;
		NightState = EPlayerNightState::InHouse;
	}
	/* ================================================================ */

	DynamicMaterial = GetMesh()->CreateDynamicMaterialInstance(0);

	// InputMappingContext ï¿½ï¿½ï¿½ï¿½
	// @PHYTODO : ï¿½Ì°ï¿½ PossessedBy ï¿½ï¿½ ï¿½Å°ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½
	// APlayerController* PlayerController = Cast<APlayerController>(GetController());
	// if (PlayerController)
	// {
	// 	UEnhancedInputLocalPlayerSubsystem* Subsystem =
	// 		ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer());
	// 	if (Subsystem)
	// 	{
	// 		Subsystem->AddMappingContext(InputMappingContext, 0);
	// 	}
	// }


	if (IsLocallyControlled())
	{
		LastControlRotation = GetControlRotation();

		GetWorldTimerManager().SetTimer(
			InteracticonTraceTimerHandle,
			this,
			&AHBCharacterPlayer::InteractionTraceTick,
			InteractionTraceInterval,
			true
		);
	}
}

void AHBCharacterPlayer::PossessedBy(AController* NewController)
{
	Super::PossessedBy(NewController);

	// if (IsLocallyControlled())
	// {
	// 	APlayerController* PlayerController = Cast<APlayerController>(GetController());
	// 	if (PlayerController)
	// 	{
	// 		ULocalPlayer* LocalPlayer = PlayerController->GetLocalPlayer();
	// 		if (LocalPlayer)
	// 		{
	// 			UEnhancedInputLocalPlayerSubsystem* Subsystem =
	// 				ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer());
	// 			if (Subsystem)
	// 			{
	// 				Subsystem->AddMappingContext(InputMappingContext, 0);
	// 			}
	// 		}
	// 	}
	// }
}

void AHBCharacterPlayer::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	if (!IsLocallyControlled())
	{
		return;
	}

	APlayerController* PlayerController = Cast<APlayerController>(GetController());
	if (PlayerController)
	{
		UEnhancedInputLocalPlayerSubsystem* Subsystem =
			ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer());
		if (Subsystem)
		{
			Subsystem->AddMappingContext(InputMappingContext, 0);
		}
	}


	UEnhancedInputComponent* EnhancedInputComponent = CastChecked<UEnhancedInputComponent>(PlayerInputComponent);
	if (EnhancedInputComponent)
	{
		EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &AHBCharacterPlayer::Move);

		EnhancedInputComponent->BindAction(AttackAction, ETriggerEvent::Triggered, this, &AHBCharacterPlayer::Attack);
		EnhancedInputComponent->BindAction(InteractionAction, ETriggerEvent::Triggered, this,
			&AHBCharacterPlayer::Interaction);

		EnhancedInputComponent->BindAction(MouseLookAction, ETriggerEvent::Triggered, this,
			&AHBCharacterPlayer::MouseLook);

		EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Triggered, this, &ACharacter::Jump);
		EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Completed, this, &ACharacter::StopJumping);

		// @PHYTODO : ï¿½Ó½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ð¹ï¿½
		EnhancedInputComponent->BindAction(StartAction, ETriggerEvent::Triggered, this, &AHBCharacterPlayer::Start);

		// ¹«±â Å»/Âø
		EnhancedInputComponent->BindAction(ToggleWeaponAction, ETriggerEvent::Triggered, this,
			&AHBCharacterPlayer::ToggleWeapon);

	}
}

void AHBCharacterPlayer::GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(AHBCharacterPlayer, PlayerColor)

	// Night ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ¼ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ï¿ï¿½ UI ï¿½ï¿½ï¿½ï¿½È­
	DOREPLIFETIME(AHBCharacterPlayer, Stamina);
	DOREPLIFETIME(AHBCharacterPlayer, NightState);
	DOREPLIFETIME(AHBCharacterPlayer, bExitedHouseThisNight);
	DOREPLIFETIME(AHBCharacterPlayer, bExitedPreviousNight);
}

void AHBCharacterPlayer::OnRep_Stamina()
{
	// RepNotify: Staminaï¿½ï¿½ ï¿½Ù²ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ HUDï¿½ï¿½ ï¿½Ý¿ï¿½
	if (!IsLocallyControlled())
	{
		return;
	}

	if (CachedHUDWidget)
	{
		
	}
	else
	{
		UE_LOG(LogTemp, Verbose, TEXT("[NightFlow] OnRep_Stamina called but CachedHUDWidget is null. Stamina=%d"), Stamina);
	}
}

void AHBCharacterPlayer::Move(const FInputActionValue& Value)
{	
	UWorld* World = Cast<UWorld>(GetWorld());
	if (!World)
	{
		return;
	}

	AHBMafiaGameState* GameState = World->GetGameState<AHBMafiaGameState>();
	if (!GameState)
	{
		return;
	}

	// ï¿½ï¿½ï¿½ï¿½ Phase ï¿½ï¿½ Day(ï¿½ï¿½ï¿½ï¿½ ï¿½Ìµï¿½ ï¿½ï¿½ ï¿½Ê±ï¿½È­ ï¿½Ü°ï¿½) ï¿½Ç´ï¿½ Discussion(ï¿½ï¿½ï¿½ ï¿½Ü°ï¿½) ï¿½Ì¸ï¿½ ï¿½Ìµï¿½ ï¿½ï¿½ï¿½ï¿½
	if (GameState->CurrentPhase == EGamePhase::Day || GameState->CurrentPhase == EGamePhase::Discussion)
	{
		return;
	}

	if (Stat->GetIsVoteTarget())
	{
		return;
	}

	const FVector2D MovementValue = Value.Get<FVector2D>();
	if (Controller)
	{
		const FVector Right = GetActorRightVector();
		AddMovementInput(Right, MovementValue.X);

		const FVector Forward = GetActorForwardVector();
		AddMovementInput(Forward, MovementValue.Y);
	}
}

// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
void AHBCharacterPlayer::Attack()
{
	// ï¿½ï¿½ï¿½â¸¦ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½È¯
	if (!bWeaponEquipped)
	{
		return;
	}
	
	if (Stat->GetIsVoteTarget())
	{
		return;
	}

	if (bCanAttack)
	{
		if (!HasAuthority())
		{
			// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ï°ï¿½ ï¿½ï¿½ï¿½ï¿½
			bCanAttack = false;

			// ï¿½ï¿½ï¿½ï¿½ ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® ï¿½Ô¼ï¿½ ï¿½ï¿½ï¿½Îµï¿½
			FTimerHandle Handle;

			GetWorldTimerManager().SetTimer(
				Handle,
				FTimerDelegate::CreateLambda(
					[&]()
					{
						bCanAttack = true;
					}
				), AttackTime, false, -1.f
			);

			// Å¬ï¿½ï¿½ï¿½Ì¾ï¿½Æ®ï¿½ï¿½ ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½ ï¿½ï¿½ï¿½
			PlayAttackAnimation();
		}

		// ServerRPC ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		ServerRPCAttack(GetWorld()->GetGameState()->GetServerWorldTimeSeconds());
	}
}

void AHBCharacterPlayer::Interaction()
{
	UWorld* World = Cast<UWorld>(GetWorld());
	if (!World)
	{
		return;
	}

	AHBMafiaGameState* GameState = World->GetGameState<AHBMafiaGameState>();
	if (!GameState)
	{
		return;
	}

	// ï¿½ï¿½ï¿½ï¿½ Phase ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ Phase ï¿½ï¿½ ï¿½Æ´Ï¸ï¿½ ï¿½ï¿½È£ï¿½Û¿ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ïµï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	if (GameState->CurrentPhase != EGamePhase::Fight && GameState->CurrentPhase != EGamePhase::Lobby)
	{
		return;
	}
	if (Stat->GetIsVoteTarget())
	{
		return;
	}

	if (IsLocallyControlled())
	{
		if (InteractionTarget != nullptr)
		{
			IHBInteractableInterface* InteractionActor = Cast<IHBInteractableInterface>(InteractionTarget);
			if (InteractionActor)
			{
				InteractionActor->Interact(this);
			}
		}

		InteractionTarget = nullptr;
	}
}

void AHBCharacterPlayer::MouseLook(const FInputActionValue& Value)
{
	const FVector2D LookAxisValue = Value.Get<FVector2D>();

	if (Controller)
	{
		AddControllerYawInput(LookAxisValue.X);
		AddControllerPitchInput(LookAxisValue.Y);
	}
}

void AHBCharacterPlayer::Start()
{
	// ï¿½ï¿½ï¿½ï¿½ï¿½Ì¸ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ð¹ï¿½
	if (!HasAuthority())
	{
		return;
	}

	ServerRPCStart();
}

void AHBCharacterPlayer::ToggleWeapon()
{
	if (MafiaAttackComp)
		MafiaAttackComp->ToggleWeapon();
}

void AHBCharacterPlayer::OnRep_PlayerColor()
{
	SetRandomBaseColor();
}

void AHBCharacterPlayer::SetRandomBaseColor()
{
	// DynamicMaterial ï¿½ï¿½ï¿½ï¿½
	if (!DynamicMaterial && GetMesh())
	{
		DynamicMaterial = GetMesh()->CreateDynamicMaterialInstance(0);
	}

	if (DynamicMaterial)
	{
		// ï¿½ï¿½ï¿½ï¿½ï¿½Ï¶ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		if (HasAuthority())
		{
			PlayerColor = FLinearColor::MakeRandomColor();

			// PlayerState ï¿½ï¿½ Color ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½È­
			AHBPlayerState* PawnState = Cast<AHBPlayerState>(GetPlayerState());
			if (PawnState)
			{
				PawnState->SyncPlayerColorFromPlayerStat(PlayerColor);
			}
		}

		// CharacterBaseColor ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ RandomColor ï¿½ï¿½ï¿½ï¿½ ï¿½Î¿ï¿½
		DynamicMaterial->SetVectorParameterValue(TEXT("CharacterBaseColor"), PlayerColor);
	}
}

void AHBCharacterPlayer::ResetBaseColor()
{
	// DynamicMaterial ï¿½ï¿½ï¿½ï¿½
	if (!DynamicMaterial && GetMesh())
	{
		DynamicMaterial = GetMesh()->CreateDynamicMaterialInstance(0);
	}

	if (DynamicMaterial)
	{
		// ï¿½ï¿½ï¿½ï¿½ï¿½Ï¶ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		if (HasAuthority())
		{
			PlayerColor = FLinearColor::White;
		}

		// CharacterBaseColor ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ RandomColor ï¿½ï¿½ï¿½ï¿½ ï¿½Î¿ï¿½
		DynamicMaterial->SetVectorParameterValue(TEXT("CharacterBaseColor"), PlayerColor);
	}
}

void AHBCharacterPlayer::InteractionTraceTick()
{
	UWorld* World = Cast<UWorld>(GetWorld());
	if (!World)
	{
		return;
	}

	AHBMafiaGameState* GameState = World->GetGameState<AHBMafiaGameState>();
	if (!GameState)
	{
		return;
	}

	// ï¿½ï¿½ï¿½ï¿½ Phase ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ Phase ï¿½ï¿½ ï¿½Æ´Ï¸ï¿½ ï¿½ï¿½È£ï¿½Û¿ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ç·ï¿½ ï¿½Çºï¿½ ï¿½ï¿½ï¿½ï¿½ X
	if (GameState->CurrentPhase != EGamePhase::Fight && GameState->CurrentPhase != EGamePhase::Lobby)
	{
		return;
	}

	const FRotator CurrentRotation = GetControlRotation();

	// ï¿½Ã¼ï¿½ ï¿½ï¿½È­ Ã¼Å© ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½Ä¡ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ê¾ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Åµ
	if (CurrentRotation.Equals(LastControlRotation, ViewAngleThreshold))
	{
		return;
	}

	LastControlRotation = CurrentRotation;

	FVector Start = FPSCameraComponent->GetComponentLocation();
	FVector End = Start + (FPSCameraComponent->GetForwardVector() * InteractionDistance);

	// Æ®ï¿½ï¿½ï¿½Ì½ï¿½ ï¿½ï¿½ï¿½ï¿½
	FHitResult Hit;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(this);

	bool bHit = GetWorld()->LineTraceSingleByChannel(
		Hit,
		Start,
		End,
		ECC_GameTraceChannel1,
		Params
	);

	AActor* HitActor = Hit.GetActor();
	if (!HitActor)
	{
		InteractionTarget = nullptr;
		return;
	}

	IHBInteractableInterface* Interactable = Cast<IHBInteractableInterface>(HitActor);
	if (Interactable)
	{
		if (Interactable->CanInteract(this))
		{
			InteractionTarget = HitActor;
		}
	}
}

void AHBCharacterPlayer::SetWeaponMesh()
{
	Super::SetWeaponMesh();

	if (bWeaponEquipped == true)
	{
		if (WeaponMesh != nullptr)
		{
			if (FPSCurrentWeapon->GetStaticMesh() == nullptr)
			{
				FPSCurrentWeapon->SetStaticMesh(WeaponMesh);
			}
		}
	}

	else
	{
		if (FPSCurrentWeapon->GetStaticMesh() != nullptr)
		{
			FPSCurrentWeapon->SetStaticMesh(nullptr);
		}
	}
}

void AHBCharacterPlayer::AttackHitCheck()
{
	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Óµï¿½ ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ Å¬ï¿½ï¿½ï¿½Ì¾ï¿½Æ®ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ È®ï¿½ï¿½
	if (IsLocallyControlled())
	{
		// ï¿½æµ¹ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ï±ï¿½
		FHitResult OutHitResult;
		FCollisionQueryParams Params(SCENE_QUERY_STAT(Attack), false, this);

		// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ï±ï¿½ (ï¿½ï¿½Å¸ï¿½, ï¿½ï¿½ï¿½ï¿½, ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½)
		float AttackRange = Stat->GetBaseStat().AttackRange;
		float AttackRadius = Stat->GetBaseStat().AttackRadius;
		float AttackDamage = Stat->GetBaseStat().AttackDamage;

		// ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ Forward ï¿½ï¿½ï¿½ï¿½, ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½/ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ï±ï¿½
		FVector Forward = GetActorForwardVector();
		FVector Start = GetActorLocation() + GetActorForwardVector() * GetCapsuleComponent()->GetScaledCapsuleRadius();
		FVector End = Start + GetActorForwardVector() * AttackRange;

		// Sweep ï¿½ï¿½ï¿½ï¿½ ï¿½æµ¹
		// @Todo: single ï¿½ï¿½ï¿½ï¿½, multi ï¿½ï¿½ï¿½ï¿½ (ï¿½Ï´ï¿½ singleï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½)
		bool HitDetected = GetWorld()->SweepSingleByChannel(
			OutHitResult,
			Start,
			End,
			FQuat::Identity,
			ECC_GameTraceChannel2,
			FCollisionShape::MakeSphere(AttackRadius),
			Params
		);

		// ï¿½æµ¹ Ã¼Å© ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ ï¿½ï¿½ï¿½ï¿½
		float HitCheckTime = GetWorld()->GetGameState()->GetServerWorldTimeSeconds();

		// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Æ´Ï¶ï¿½ï¿½
		if (!HasAuthority())
		{
			// ï¿½æµ¹ ï¿½ß´Ù¸ï¿½
			if (HitDetected)
			{
				// ï¿½ï¿½ï¿½ï¿½RPC ï¿½ï¿½ ï¿½æµ¹ ï¿½ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
				ServerRPCNotifyHit(OutHitResult, HitCheckTime);
			}

			// ï¿½æµ¹ ï¿½ï¿½ï¿½ß´Ù¸ï¿½
			else
			{
				// ï¿½ï¿½ï¿½ï¿½RPC ï¿½ï¿½ ï¿½Ì½ï¿½ ï¿½ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
				ServerRPCNotifyMiss(Start, End, Forward, HitCheckTime);
			}
		}

		// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		else
		{
			// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ Ç¥ï¿½ï¿½
			FColor DebugColor = HitDetected ? FColor::Green : FColor::Red;
			DrawDebugAttackRange(DebugColor, Start, End, Forward);

			// ï¿½æµ¹ ï¿½ß´Ù¸ï¿½
			if (HitDetected)
			{
				// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
				AttackHitConfirm(OutHitResult.GetActor());
			}
		}
	}
}

void AHBCharacterPlayer::AttackHitConfirm(AActor* HitActor)
{
	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	if (HasAuthority())
	{
		// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		float AttackDamage = Stat->GetBaseStat().AttackDamage;

		// ï¿½Î‹Hï¿½ï¿½ ï¿½ï¿½ó¿¡°ï¿½ TakeDamage ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		FDamageEvent DamageEvent;
		HitActor->TakeDamage(AttackDamage, DamageEvent, GetController(), this);

		AHBMafiaGameState* GameState = GetWorld()->GetGameState<AHBMafiaGameState>();
		if (GameState && GameState->CurrentPhase == EGamePhase::Fight)
		{
			UHBGameVoteSubsystem* VoteSubsystem = GetGameInstance()->GetSubsystem<UHBGameVoteSubsystem>();
			if (VoteSubsystem)
			{
				// @PHYTODO : Top3 ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
			}
		}
	}
}

void AHBCharacterPlayer::DrawDebugAttackRange(const FColor& DrawColor, FVector TraceStart, FVector TraceEnd,
	FVector Forward)
{
#if ENABLE_DRAW_DEBUG

	const float AttackRange = Stat->GetBaseStat().AttackRange;
	const float AttackRadius = Stat->GetBaseStat().AttackRadius;
	FVector CapsuleOrigin = TraceStart + (TraceEnd - TraceStart) * 0.5f;
	float CapsuleHalfHeight = AttackRange * 0.5f;

	DrawDebugCapsule(GetWorld(), CapsuleOrigin, CapsuleHalfHeight, AttackRadius,
		FRotationMatrix::MakeFromZ(Forward).ToQuat(), DrawColor, false, 5.0f);

#endif
}

void AHBCharacterPlayer::ServerRPCNotifyHit_Implementation(const FHitResult& HitResult, float HitCheckTime)
{
	// ï¿½æµ¹ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	AActor* HitActor = HitResult.GetActor();

	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ï¸ï¿½
	if (HitActor)
	{
		// ï¿½æµ¹ ï¿½ß»ï¿½ ï¿½ï¿½Ä¡, ï¿½æµ¹ ï¿½ß»ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ù¿ï¿½ï¿½ ï¿½Ú½ï¿½, ï¿½Ù¿ï¿½ï¿½ ï¿½Ú½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½îµ¥ ï¿½ï¿½ï¿½ï¿½
		FVector HitLocation = HitResult.Location;
		FBox HitBox = HitActor->GetComponentsBoundingBox();
		FVector ActorBoxCenter = HitBox.GetCenter();

		// ï¿½æµ¹ ï¿½ß»ï¿½ ï¿½ï¿½Ä¡ï¿½ï¿½ ï¿½Ù¿ï¿½ï¿½ ï¿½Ú½ï¿½ï¿½ï¿½ ï¿½ß°ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½æµ¹ Ã¼Å© ï¿½Ö¼ï¿½ ï¿½Å¸ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		if (FVector::DistSquared(HitLocation, ActorBoxCenter) <= AcceptCheckDistance * AcceptCheckDistance)
		{
			// ï¿½æµ¹ ï¿½ï¿½ ï¿½Ìºï¿½Æ® ï¿½ï¿½ï¿½ï¿½
			AttackHitConfirm(HitActor);
		}
		else
		{
			UE_LOG(LogTemp, Warning, TEXT("HitTest Reject"));
		}

		// ï¿½æµ¹ ï¿½ï¿½ Notify ï¿½Ì´ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ã·ï¿½ï¿½ï¿½ Green ï¿½ï¿½ ï¿½Ö¾îµµ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½
		DrawDebugAttackRange(FColor::Green, HitResult.TraceStart, HitResult.TraceEnd,
			HitActor->GetActorForwardVector());
	}
}

bool AHBCharacterPlayer::ServerRPCNotifyHit_Validate(const FHitResult& HitResult, float HitCheckTime)
{
	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ 0 (Ã³ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½)
	if (LastAttackStartTime == 0.f)
	{
		return true;
	}
	// ï¿½æµ¹ Ã¼Å© ï¿½Ã°ï¿½ï¿½Ì¶ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ì°ï¿½ ï¿½Ö¼ï¿½ Ã¼Å© ï¿½ï¿½ï¿½Ýºï¿½ï¿½ï¿½ Ä¿ï¿½ï¿½ Ã¼Å© ï¿½ï¿½ï¿½ï¿½
	return (HitCheckTime - LastAttackStartTime) > AcceptMinCheckTime;
}

void AHBCharacterPlayer::ServerRPCNotifyMiss_Implementation(FVector_NetQuantize TraceStart,
	FVector_NetQuantize TraceEnd,
	FVector_NetQuantizeNormal TraceDir, float HitCheckTime)
{
	// ï¿½æµ¹ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½×¸ï¿½ï¿½ï¿½
	DrawDebugAttackRange(FColor::Red, TraceStart, TraceEnd, TraceDir);
}

bool AHBCharacterPlayer::ServerRPCNotifyMiss_Validate(FVector_NetQuantize TraceStart, FVector_NetQuantize TraceEnd,
	FVector_NetQuantizeNormal TraceDir, float HitCheckTime)
{
	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ 0 (Ã³ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½)
	if (LastAttackStartTime == 0.f)
	{
		return true;
	}
	// ï¿½æµ¹ Ã¼Å© ï¿½Ã°ï¿½ï¿½Ì¶ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ì°ï¿½ ï¿½Ö¼ï¿½ Ã¼Å© ï¿½ï¿½ï¿½Ýºï¿½ï¿½ï¿½ Ä¿ï¿½ï¿½ Ã¼Å© ï¿½ï¿½ï¿½ï¿½
	return (HitCheckTime - LastAttackStartTime) > AcceptMinCheckTime;
}

void AHBCharacterPlayer::PlayAttackAnimation()
{
	// Ä³ï¿½ï¿½ï¿½ï¿½ ï¿½Þ½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Å¸ï¿½ï¿½ ï¿½ï¿½ï¿½
	UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance();
	if (AnimInstance)
	{
		AnimInstance->StopAllMontages(0.f);
		AnimInstance->Montage_Play(AttackMontage);
	}

	// @Todo: 1ï¿½ï¿½Äª ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Å¸ï¿½ï¿½ ï¿½ï¿½ï¿½
	UAnimInstance* FPSAnimInstance = FPSMeshComponent->GetAnimInstance();
	if (FPSAnimInstance)
	{
	}
}

void AHBCharacterPlayer::SetupHUDWidget(UHBUserHUDWidget* InHUDWidget)
{
	if (InHUDWidget)
	{
		//@PHYTODO : ï¿½Ã°ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ Ã³ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		AHBMafiaGameState* GameState = GetWorld()->GetGameState<AHBMafiaGameState>();
		if (GameState)
		{
			InHUDWidget->UpdatePhase(GameState->CurrentPhase);
			InHUDWidget->UpdateRemainingTime(GameState->RemainingTime);
			InHUDWidget->UpdateDate(GameState->Date);

			GameState->OnGamePhaseChanged.AddUObject(InHUDWidget, &UHBUserHUDWidget::UpdatePhase);
			GameState->OnRemainingTimeChanged.AddUObject(InHUDWidget, &UHBUserHUDWidget::UpdateRemainingTime);
			GameState->OnDateChanged.AddUObject(InHUDWidget,&UHBUserHUDWidget::UpdateDate);
			GameState->OnTopDamagePlayersChanged.AddUObject(InHUDWidget, &UHBUserHUDWidget::UpdateCurrentFightInfo);
		}

		// HUDï¿½ï¿½ Stamina ï¿½ï¿½ï¿½ï¿½: ï¿½Ê±â°ª ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ Ä³ï¿½ï¿½ (ï¿½ï¿½ï¿½ï¿½ Å¬ï¿½ï¿½ï¿½Ì¾ï¿½Æ®ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½)
		if (IsLocallyControlled())
		{
			CachedHUDWidget = InHUDWidget;
		}
	}
}

// @PHYTODO : ï¿½ï¿½ï¿½ï¿½ ï¿½Ð¹ï¿½ ï¿½Ó½ï¿½ È®ï¿½Î¿ï¿½
void AHBCharacterPlayer::ServerRPCStart_Implementation()
{
	UE_LOG(LogTemp, Log, TEXT("ServerRPCStart Call"));
	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Æ´Ï¶ï¿½ï¿½
	if (!HasAuthority())
	{
		return;
	}

	UGameInstance* GameInstance = GetGameInstance();
	if (GameInstance)
	{
		// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		AHBVillageGameMode* VillageGameMode = Cast<AHBVillageGameMode>(GetWorld()->GetAuthGameMode());
		if (VillageGameMode)
		{
			// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì¸ï¿½
			if (VillageGameMode->GetIsGamePlaying())
			{
				VillageGameMode->CheatPhaseChange();
				//VillageGameMode->StopGame();
			}

			// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
			else
			{
				VillageGameMode->StartGame();
			}
		}
		// UHBGameFlowSubsystem* GameFlowSubsystem = GameInstance->GetSubsystem<UHBGameFlowSubsystem>();
		// if (GameFlowSubsystem)
		// {
		// 	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì¸ï¿½
		// 	if (GameFlowSubsystem->GetIsGamePlaying())
		// 	{
		// 		// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		// 		GameInstance->GetSubsystem<UHBGameFlowSubsystem>()->StopGame();
		// 	}
		// 	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		// 	else
		// 	{
		// 		// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		// 		GameInstance->GetSubsystem<UHBGameFlowSubsystem>()->StartGame();
		// 	}
		// }

		//OnRep_PlayerColor();
	}
}

void AHBCharacterPlayer::ClientRPCPlayAnimation_Implementation(AHBCharacterPlayer* CharacterToPlay)
{
	// CharacterToPlay ï¿½ï¿½ ï¿½ï¿½È¿ï¿½Ï¸ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½ ï¿½ï¿½ï¿½
	if (CharacterToPlay)
	{
		CharacterToPlay->PlayAttackAnimation();
	}
}

void AHBCharacterPlayer::ServerRPCAttack_Implementation(float AttackStartTime)
{
	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã·ï¿½ï¿½×¸ï¿½ falseï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	bCanAttack = false;

	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ OnRep È£ï¿½ï¿½ï¿½ï¿½ ï¿½ÈµÇ´ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ È£ï¿½ï¿½
	// ï¿½Ï´ï¿½ ï¿½Ù²ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ Pass

	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ì¸ï¿½ ï¿½ï¿½ï¿½ï¿½ (ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½)
	AttackTimeDifference = GetWorld()->GetTimeSeconds() - AttackStartTime;

	// ï¿½Ø´ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ 0ï¿½Ê¿ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½ ï¿½ï¿½ï¿½Ìºï¿½ï¿½ï¿½ ï¿½ï¿½Â¦ Âªï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ (Clamp)
	AttackTimeDifference = FMath::Clamp(AttackTimeDifference, 0.f, AttackTime - 0.1f);

	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ù½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö´ï¿½ Å¸ï¿½Ì¸ï¿½ ï¿½ï¿½ï¿½ï¿½
	FTimerHandle Handle;
	GetWorldTimerManager().SetTimer(
		Handle,
		FTimerDelegate::CreateLambda(
			[&]()
			{
				bCanAttack = true;
			}
		), AttackTime - AttackTimeDifference, false, -1.f
	);

	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½Ì¹ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	LastAttackStartTime = AttackStartTime;

	// ï¿½ï¿½ï¿½ï¿½ ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½ ï¿½ï¿½ï¿½ (ï¿½ï¿½ï¿½ï¿½)
	PlayAttackAnimation();

	// ï¿½Ù¸ï¿½ Å¬ï¿½ï¿½ï¿½Ì¾ï¿½Æ®ï¿½ï¿½ï¿½ï¿½ ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½ ï¿½ï¿½ï¿½ (ï¿½ï¿½ï¿½ï¿½ ï¿½ß»ï¿½ Å¬ï¿½ï¿½ X, ï¿½ï¿½ï¿½ï¿½ X)
	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½å¿¡ ï¿½Ö´ï¿½ PlayerController ï¿½ï¿½ï¿½ï¿½ ï¿½Þ¾Æ¿ï¿½
	for (APlayerController* PlayerController : TActorRange<APlayerController>(GetWorld()))
	{
		// PlayerController ï¿½ï¿½ ï¿½ï¿½È¿ï¿½Ï°ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Æ®ï¿½Ñ·ï¿½ï¿½ï¿½ ï¿½Æ´Ï¸ï¿½
		if (PlayerController && GetController() != PlayerController)
		{
			// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Æ®ï¿½Ñ·ï¿½ï¿½ï¿½ ï¿½Æ´Ï¸ï¿½
			if (!PlayerController->IsLocalController())
			{
				AHBCharacterPlayer* OtherPlayer = Cast<AHBCharacterPlayer>(PlayerController->GetPawn());
				if (OtherPlayer)
				{
					// Å¬ï¿½ï¿½ï¿½Ì¾ï¿½Æ®ï¿½ï¿½ PlayAnimation ï¿½ï¿½ ï¿½ï¿½ï¿½
					OtherPlayer->ClientRPCPlayAnimation(this);
				}
			}
		}
	}
}

bool AHBCharacterPlayer::ServerRPCAttack_Validate(float AttackStartTime)
{
	// ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½È¿ï¿½ï¿½ï¿½ï¿½ Ã¼Å©
	if (LastAttackStartTime == 0.f)
	{
		return true;
	}

	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½Ö´Ï¸ï¿½ï¿½Ì¼ï¿½ ï¿½ï¿½ï¿½Ìºï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ true ï¿½ï¿½È¯
	// Âªï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ï´Â°Å¶ï¿½ ï¿½Ç´ï¿½ï¿½Ø¼ï¿½ false
	return (AttackStartTime - LastAttackStartTime) > AttackTime;
}

/* ================= Night Flow ================= */

void AHBCharacterPlayer::EnterHouse()
{
	if (!HasAuthority()) return;

	// ï¿½ï¿½ ï¿½ï¿½ï¿½Â¿ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ç¹ï¿½ ï¿½ï¿½ï¿½ï¿½
	AHBMafiaGameState* GS = GetWorld()->GetGameState<AHBMafiaGameState>();
	if (!GS || !GS->IsNight())
	{
		return;
	}

	NightState = EPlayerNightState::InHouse;

	// ï¿½Ì¹ï¿½ ï¿½ã¿¡ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ È¸ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	if (!bExitedHouseThisNight)
	{
		StartStaminaRecovery();
	}
}

void AHBCharacterPlayer::ExitHouse()
{
	UE_LOG(LogTemp, Log, TEXT("ExitHouse called"));

	if (!HasAuthority()) return;

	// ï¿½Ì¹ï¿½ ï¿½ï¿½ï¿½Ì¸ï¿½ ï¿½ßºï¿½ Ã³ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	if (NightState == EPlayerNightState::Outside)
	{
		return;
	}

	AHBMafiaGameState* GS = GetWorld()->GetGameState<AHBMafiaGameState>();
	if (!GS || !GS->IsNight())
	{
		// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ Night Flow ï¿½ï¿½ï¿½Â¸ï¿½ ï¿½Çµå¸®ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		return;
	}

	NightState = EPlayerNightState::Outside;

	// ï¿½Ì¹ï¿½ ï¿½ã¿¡ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½
	bExitedHouseThisNight = true;

	// ï¿½ï¿½ï¿½Â¹Ì³ï¿½(ï¿½ï¿½ï¿½) 1ï¿½ï¿½ ï¿½Ò¸ï¿½ ? ï¿½ï¿½ï¿½ ï¿½Ò¸ï¿½ ï¿½ï¿½Ä¢
	Stamina = FMath::Max(Stamina - 1, 0);
	OnStaminaChanged.Broadcast(Stamina);

	// ï¿½ï¿½ ï¿½ï¿½ï¿½Ì¶ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ì¹ï¿½ ï¿½ï¿½ È¸ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ß´ï¿½
	StopStaminaRecovery();

	UE_LOG(LogTemp, Warning,
		TEXT("[NightFlow] ExitHouse | Stamina: %d | ExitedThisNight: true"),
		Stamina);
}

void AHBCharacterPlayer::StartStaminaRecovery()
{
	if (!HasAuthority()) return;

	// ï¿½Ì¹ï¿½ È¸ï¿½ï¿½ ï¿½ï¿½ï¿½Ì¸ï¿½ ï¿½ßºï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	if (GetWorldTimerManager().IsTimerActive(StaminaRecoverTimerHandle))
	{
		return;
	}

	GetWorldTimerManager().SetTimer(
		StaminaRecoverTimerHandle,
		this,
		&AHBCharacterPlayer::RecoverStaminaTick,
		StaminaRecoverInterval,
		true
	);
}

void AHBCharacterPlayer::StopStaminaRecovery()
{
	if (!HasAuthority()) return;

	GetWorldTimerManager().ClearTimer(StaminaRecoverTimerHandle);
}

void AHBCharacterPlayer::RecoverStaminaTick()
{
	if (!HasAuthority()) return;

	// ï¿½Ì¹ï¿½ ï¿½ã¿¡ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ È¸ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	if (bExitedHouseThisNight)
	{
		StopStaminaRecovery();
		return;
	}

	AHBMafiaGameState* GS = GetWorld()->GetGameState<AHBMafiaGameState>();
	if (!GS || !GS->IsNight())
	{
		StopStaminaRecovery();
		return;
	}

	// ï¿½ï¿½ ï¿½È¿ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ È¸ï¿½ï¿½
	if (NightState != EPlayerNightState::InHouse)
	{
		StopStaminaRecovery();
		return;
	}

	const int32 OldStamina = Stamina;
	Stamina = FMath::Min(Stamina + StaminaRecoverAmount, MaxStamina);

	UE_LOG(LogTemp, Log,
		TEXT("[NightFlow] Recover %d -> %d"),
		OldStamina, Stamina);

	// ï¿½Ö´ï¿½Ä¡ï¿½ï¿½ È¸ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	if (Stamina >= MaxStamina)
	{
		StopStaminaRecovery();
	}
}

void AHBCharacterPlayer::ResetNightState()
{
	if (!HasAuthority()) return;

	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Î¸ï¿½ ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½)
	bExitedPreviousNight = bExitedHouseThisNight;

	// ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½âº» ï¿½ï¿½ï¿½ï¿½ ï¿½Ê±ï¿½È­ (ï¿½Ì¹ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½)
	bExitedHouseThisNight = false;
	NightState = EPlayerNightState::InHouse;

	// È¤ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ð¸£´ï¿½ Å¸ï¿½Ì¸ï¿½ ï¿½ï¿½ï¿½ï¿½
	StopStaminaRecovery();

	UE_LOG(LogTemp, Log,
		TEXT("[NightFlow] ResetNightState | Stamina: %d | PrevExited: %s"),
		Stamina, bExitedPreviousNight ? TEXT("true") : TEXT("false"));
}

void AHBCharacterPlayer::ProcessNightEnd()
{
	if (!HasAuthority()) return;

	// ï¿½ï¿½Ä¢: "ï¿½ï¿½ï¿½ï¿½(ï¿½Ù·ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½)ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½, ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½(ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½) ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Â¹Ì³ï¿½ +1 È¸ï¿½ï¿½"
	// ï¿½ï¿½ï¿½â¼­ï¿½ï¿½ 'ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½'(-> ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½) È£ï¿½ï¿½Ç¾ï¿½, bExitedPreviousNight ï¿½ï¿½ ï¿½Ù·ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Ïµï¿½ ï¿½ï¿½,
	// bExitedHouseThisNight ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½(ï¿½ï¿½ ï¿½ï¿½)ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ß´ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½.
	if (bExitedPreviousNight && !bExitedHouseThisNight)
	{
		const int32 Old = Stamina;
		Stamina = FMath::Min(Stamina + 1, MaxStamina);
		UE_LOG(LogTemp, Log,
			TEXT("[NightFlow] ProcessNightEnd: Recovered %d -> %d (PrevExited true, ThisNight no exit)"),
			Old, Stamina);
	}

	// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½Å¬ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½Ã·ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ (ï¿½ï¿½ï¿½ï¿½ bExitedPreviousNightï¿½ï¿½ ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Î·ï¿½ ï¿½ï¿½ï¿½ï¿½)
	bExitedPreviousNight = bExitedHouseThisNight;
}